name: black_hole_flutter_example
publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  black_hole_flutter:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: f59c0bb55b5cc611b67c60c9eaa35dc34a927310

flutter:
  uses-material-design: true
