name: black_hole_flutter_example
description: 'Example for 🛠 black_hole_flutter, a package absorbing all Flutter utility functions'
publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  black_hole_flutter:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
