name: black_hole_flutter
description: A package absorbing all Flutter utility functions, including extension functions and commonly used widgets
version: 1.2.0
repository: https://github.com/JonasWanke/black_hole_flutter
screenshots:
  - description: Fancy buttons feature a loading state
    path: doc/widgets-buttons.gif

environment:
  sdk: ^3.12.0
  flutter: '>=3.47.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  material_ui: ^1.1.1
  meta: ^1.3.0

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 20b9a50f30efe39b17c9d20a6189027af4742526
